<?php
/**
 * Created by PhpStorm.
 * User: Wilfried Yoro
 * Date: 29/11/2018
 * Time: 08:31
 */
namespace  App\Form;

use App\Entity\Localisation;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use \Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class  GestionnaireType extends AbstractType{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('typeGest', ChoiceType::class, [
                'label' => 'Qui êtes vous ? ',
                'choices'=> [
                    'Particulier' => 'particulier',
                    'Agence Immobilière' => 'agence'
                ],
                'required'=> true
            ])

            ->add('nomGest', TextType::class, [
                'label' => 'Nom et Prénoms / Nom Agence Immobilière'
            ])

            ->add('telGest', TextType::class, [
                'label' => 'Téléphone'
            ])

            ->add('emailGest', EmailType::class, [
                'label' => 'Adresse Email',
                'required' => true
            ])

            ->add('localisation', EntityType::class, [
                'class' => Localisation::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.localisation', 'ASC');
                },
                'choice_label' => 'localisation'
            ])

            ->add('infosComplement', TextareaType::class,[
                'label' => 'Infos Complémentaires',
                'required' => false
            ])
            ->add('inscription', SubmitType::class);
    }
}