<?php
/**
 * Created by PhpStorm.
 * User: Wilfried Yoro
 * Date: 29/11/2018
 * Time: 08:31
 */
namespace  App\Form;

use \Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

class  NewsletterType extends AbstractType{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('emailAbonne', EmailType::class, [
                'label' => 'Adresse Email',
                'required' => true,
                'attr'  => array('class' => 'white')
            ])

            ->add('abonner', SubmitType::class,[
                'label' =>'S\'abonner',
                'attr'  => array('class' => 'btn btn-large orange pulse black-text')
            ]);
    }
}