<?php
/**
 * Created by PhpStorm.
 * User: Wilfried Yoro
 * Date: 29/11/2018
 * Time: 08:31
 */
namespace  App\Form;

use App\Entity\Localisation;
use App\Entity\NiveauEtude;
use App\Entity\PieceIdentite;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use \Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class  PrestataireType extends AbstractType{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('nomPrest', TextType::class, [
                'label' => 'Nom'
            ])

            ->add('prenomPrest',TextType::class, [
                'label' => 'Prénoms'
            ])

            ->add('telPrest', TextType::class, [
                'label' => 'Téléphone'
            ])

            ->add('emailPrest', EmailType::class, [
                'label' => 'Adresse Email',
                'required' => true
            ])

            ->add('localisation', EntityType::class, [
                'class' => Localisation::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.localisation', 'ASC');
                },
                'choice_label' => 'localisation'
            ])

            ->add('nomPiece', EntityType::class, [
                'class' => PieceIdentite::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.nomPiece');
                },
                'choice_label' => 'nomPiece',
                'label'=>'Nature de la pièce'
            ])

            ->add('numPiece', TextType::class,[
                'label' => 'Numéro de la Piece',
                'required' => true
            ])

            ->add('niveau', EntityType::class, [
                'class' => NiveauEtude::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.niveau');
                },
                'choice_label' => 'niveau',
                'label'=>'Niveau d\'étude'
            ])

            ->add('inscription', SubmitType::class, [
                'attr'  => array('class' => 'btn btn-danger btn-large')
            ]);
    }
}